export default{
  api:{
    getContactList:{
      url:"/contactList",
      method:"get",
      hooks:{
        beforeReq(){console.log("beforeReq")},
        afterReq(){console.log("afterReq")},
      }
    },
    addContact:{
      url:"/contact/new/form",
      method:"post",
      isForm:true
    },
    addContact:{
      url:"/contact/new/json",
      method:"post"
    },
    updateContact:{
      url:"/contact/edit",
      method:"put"
    },
    deleteContact:{
      url:"/contact",
      method:"delete"
    },
  }
}